name: Terraform Plan Debug

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_LOG: DEBUG        # Activa logs detallados de Terraform
      TF_LOG_PATH: terraform.log  # Guarda el log en archivo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show environment variables (masked sensitive data)
        run: |
          echo "AWS_REGION is $AWS_REGION"
          echo "AWS_ACCESS_KEY_ID is set: ${AWS_ACCESS_KEY_ID:+yes}"
          echo "AWS_SECRET_ACCESS_KEY is set: ${AWS_SECRET_ACCESS_KEY:+yes}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Upload Terraform debug log
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: terraform-debug-log
          path: terraform.log
