name: Terraform Plan Debug

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_LOG: DEBUG
      TF_LOG_PATH: terraform.log

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Mostrar variables de entorno (seguras)
        run: |
          echo "AWS_REGION: $AWS_REGION"
          echo "AWS_ACCESS_KEY_ID está definida: ${AWS_ACCESS_KEY_ID:+sí}"
          echo "AWS_SECRET_ACCESS_KEY está definida: ${AWS_SECRET_ACCESS_KEY:+sí}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Subir log de Terraform (si falla)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: terraform-debug-log
          path: terraform/terraform.log

